### PR TITLE
Add squirrel binaries to cmake build

### PR DESCRIPTION
**Pull request by neochief**
I've added the missing standalone compiler and sqdbg binary to cmake build script. The code for binaries is taken from current squirrel distribution for 3.0.7 + minor formatting fixes.

### CODE REVIEW

**Comment by tobbi** [comment]
Hey, I actually didn't see this until now. Can you update the pull request for the newly released Squirrel version?

**Comment by maxteufel** [comment]
Can we be sure this doesn't conflict with distribution-provided squirrel binaries?

**Comment by tobbi** [comment]
I don't know, and you probably know more about distribution-provided squirrel binaries than I do.

Fact is: When updating squirrel, I only replaced files that actually needed replacing, nothing more. So, our clone is not a complete squirrel clone, by any means.

**Comment by maths22** [comment]
This repository is no longer in active use (as of today), so I will close this pull request.  However, this repository will be retained (at least in the short term) for archival purposes.

**Pull request closed without merging**
